site_name: chcyru
site_url: https://ychiucco.github.io

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: orange
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: orange
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode


nav:
  - Scacchi:
  - Libri:
  - Musica:

  